### ISSUE TITLE
mac m2 arm架构无法正常安装

### ISSUE THREAD

**Issue by Hetystars** [hango-io/hango-gateway#53]
**Describe the bug**
**执行 sh install.sh 完成后，提示如下：**
hango pod running
-e [hango-install][2023-03-19 17:32:18] hango verfied ok
Init error, init_hango can be run independently

============================== Common mistakes ==============================

1.The same gateway has been created, please go to the hango-console to check
2.hango-portal is unhealthy, please check the hango-portal pod status

**执行sh check.sh，显示如下**
NAME                              READY   STATUS      RESTARTS   AGE
hango-api-plane-6489ffc5f-lbtj5   0/1     OOMKilled   1          5m49s
hango-istiod-75cb8bd5fc-fxxdb     1/1     Running     0          5m49s
hango-portal-b99c964d7-xgqmf      1/1     Running     0          5m49s
hango-proxy-68b98fb64b-pmmbv      1/1     Running     0          5m49s
hango-ui-76b4d85469-z7gfj         1/1     Running     0          5m49s
istio-e2e-app-54dc57b7ff-d8znz    1/1     Running     0          5m49s
slime-hango-5d6c5fc5bc-z9h7w      1/1     Running     0          5m49s

**执行kubectl -n hango-system logs -f hango-api-plane-6489ffc5f-lbtj5，看到部分异常日志如下**
19-Mar-2023 17:35:23.339 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
	org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:711)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1177)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: java.lang.NullPointerException
		at io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext.fromCrd(CustomResourceDefinitionContext.java:52)
		at org.hango.cloud.cache.K8sResourceCache.registryInformer(K8sResourceCache.java:83)
		at org.hango.cloud.cache.K8sResourceCache.initInformer(K8sResourceCache.java:68)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
		at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
		at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
		at java.util.ArrayList.forEach(ArrayList.java:1259)
		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
		at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:358)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4940)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
19-Mar-2023 17:35:23.339 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [/usr/local/tomcat/webapps/ROOT]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:715)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1177)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:711)
		... 9 more
	Caused by: java.lang.NullPointerException
		at io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext.fromCrd(CustomResourceDefinitionContext.java:52)
		at org.hango.cloud.cache.K8sResourceCache.registryInformer(K8sResourceCache.java:83)
		at org.hango.cloud.cache.K8sResourceCache.initInformer(K8sResourceCache.java:68)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
		at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
		at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
		at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
		at java.util.ArrayList.forEach(ArrayList.java:1259)
		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
		at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:358)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4940)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
**To Reproduce**
sh install.sh
sh check.sh

**Expected behavior**
正常安装

**Additional context**
Add any other context about the problem here, e.g.
- Kubernetes version: minikube v1.29.0  Kubernetes v1.26.1 on Docker 20.10.23
- OS: Darwin 13.2.1 (arm64) mac m2
- hango-gateway version: v1.31

**Comment by trickMin** [comment]
Hango新版本镜像已配置最小管控面组件JVM资源占用，实际使用可通过修改镜像打包脚本进行组件重新打包，但建议16G左右的k8s集群可用空间
